#!/usr/bin/env bun
// Scaffolds placeholder audio for the phonics learning path and emits the manifest
// that drives the real ElevenLabs bulk pass.
//
//   bun run scripts/scaffold-phonics-audio.ts
//
// For every clip in `buildPhonicsAudioManifest()` it drops a placeholder mp3 (a
// copy of a tiny existing sfx blip) at `apps/web/public/<path>` IF one is not
// already there — so a later real-audio pass that overwrites individual files is
// never clobbered. It also (re)writes a machine manifest (`audio-manifest.json`)
// and a human checklist (`AUDIO-MANIFEST.md`) under `docs/phonics/`.
//
// Audio is path-based voice (`new Audio(...).play()`), NOT a SoundId — a missing
// or placeholder clip fails silently, so this never blocks the gate.

import { mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

import { buildPhonicsAudioManifest } from "../packages/schemas/src/data/phonics";

const REPO_ROOT = resolve(import.meta.dir, "..");
const PUBLIC_DIR = join(REPO_ROOT, "apps/web/public");
const DOCS_DIR = join(REPO_ROOT, "docs/phonics");
const PLACEHOLDER_SOURCE = join(PUBLIC_DIR, "sfx/ui/board-mode-gathering.mp3");

const manifest = buildPhonicsAudioManifest();
const placeholder = Bun.file(PLACEHOLDER_SOURCE);
if (!(await placeholder.exists())) {
  throw new Error(`placeholder source missing: ${PLACEHOLDER_SOURCE}`);
}

let created = 0;
let skipped = 0;
for (const entry of manifest) {
  const target = join(PUBLIC_DIR, entry.path);
  if (await Bun.file(target).exists()) {
    skipped += 1;
    continue;
  }
  mkdirSync(dirname(target), { recursive: true });
  await Bun.write(target, placeholder);
  created += 1;
}

// Machine manifest for the bulk-synthesis pass.
mkdirSync(DOCS_DIR, { recursive: true });
await Bun.write(join(DOCS_DIR, "audio-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);

// Human checklist.
const vowelRows = manifest
  .filter((entry) => entry.kind === "vowel")
  .map((entry) => `| \`${entry.path}\` | ${entry.label} | ${entry.text} |`)
  .join("\n");
const wordRows = manifest
  .filter((entry) => entry.kind === "word")
  .map((entry) => `| \`${entry.path}\` | ${entry.label} | ${entry.text} |`)
  .join("\n");
const md = `# Phonics audio manifest

Generated by \`scripts/scaffold-phonics-audio.ts\`. ${manifest.length} clips total.
Placeholders are copies of a tiny sfx blip; replace each with a real ElevenLabs
clip at the same path. Re-running the scaffolder will NOT overwrite real audio.

## Vowel prompt sounds (${manifest.filter((e) => e.kind === "vowel").length})

| Path | Vowel | Say |
|---|---|---|
${vowelRows}

## Word readouts (${manifest.filter((e) => e.kind === "word").length})

| Path | Word | Say |
|---|---|---|
${wordRows}
`;
await Bun.write(join(DOCS_DIR, "AUDIO-MANIFEST.md"), md);

await Bun.write(
  Bun.stdout,
  `phonics audio: ${created} placeholder(s) created, ${skipped} already present, ${manifest.length} total clips.\n` +
    "manifest written to docs/phonics/audio-manifest.json and AUDIO-MANIFEST.md\n",
);
